=== asseco-see/AdaptiveCards/source/nodejs/schemas/extensions/schema/schema.json
{
	"definitions": {
		"contribution": {
			"$schema": "http://json-schema.org/draft-06/schema#",
			"id": "http://adaptivecards.io/schemas/adaptive-card.json",
			"definitions": {
				"Class": {
					"description": "Expresses a class",
					"properties": {
						"classType": {
							"enum": [
								"Class"
							],
							"description": "Must be `Class`"
						},
						"type": {
							"type": "string",
							"description": "The name of the class"
						},
						"description": {
							"type": "string",
							"description": "A description of the class"
						},
						"properties": {
							"type": "object",
							"additionalProperties": {
								"$ref": "#/definitions/Property"
							},
							"description": "Properties of the class"
						},
						"isAbstract": {
							"type": "boolean",
							"description": "Specifies whether this class is abstract"
						},
						"extends": {
							"type": "string",
							"description": "Class that this class extends from"
						},
						"shorthand": {
							"type": "string",
							"description": "Name of one of the properties that represents a shorthand version of this class"
						},
						"$schema": {
							"type": "string",
							"format": "uri",
							"description": "JSON schema for the JSON file"
						}
					},
					"type": "object",
					"additionalProperties": false,
					"required": []
				},
				"Enum": {
					"description": "Expresses an enum",
					"properties": {
						"classType": {
							"enum": [
								"Enum"
							],
							"description": "Must be `Enum`"
						},
						"type": {
							"type": "string",
							"description": "The name of the enum"
						},
						"values": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/EnumValue"
							},
							"description": "The values in the enum"
						},
						"$schema": {
							"type": "string",
							"format": "uri",
							"description": "JSON schema for the JSON file"
						}
					},
					"type": "object",
					"additionalProperties": false,
					"required": [
						"type",
						"values"
					]
				},
				"EnumValue": {
					"description": "Expresses an enum value",
					"anyOf": [
						{
							"type": "string",
							"description": "The name of the enum value"
						},
						{
							"type": "object",
							"properties": {
								"classType": {
									"enum": [
										"EnumValue"
									],
									"description": "Must be `EnumValue`"
								},
								"value": {
									"type": "string",
									"description": "The name of the enum value"
								},
								"description": {
									"type": "string",
									"description": "A description of the enum value"
								}
							},
							"required": [
								"value"
							],
							"additionalProperties": false
						}
					]
				},
				"Property": {
					"properties": {
						"classType": {
							"enum": [
								"Property"
							],
							"description": "Must be `Property`"
						},
						"type": {
							"type": "string",
							"description": "The type of the property"
						},
						"description": {
							"type": "string",
							"description": "A description of the property"
						},
						"version": {
							"type": "string",
							"description": "The version when the property is introduced"
						},
						"required": {
							"type": "boolean",
							"description": "Specifies whether the property is required",
							"default": false
						},
						"shorthands": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/Property"
							},
							"description": "Shorthand alternatives for this property"
						},
						"default": {
							"description": "The default value of this property"
						},
						"examples": {
							"type": "array",
							"description": "Examples of this value"
						}
					},
					"type": "object",
					"additionalProperties": false,
					"required": [
						"type"
					]
				}
			},
			"anyOf": [
				{
					"allOf": [
						{
							"$ref": "#/definitions/Class"
						}
					]
				},
				{
					"allOf": [
						{
							"$ref": "#/definitions/Enum"
						}
					],
					"required": [
						"classType"
					]
				}
			]
		}
	},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://example.com/object1619001505.json",
	"title": "Root",
	"type": "object",
	"required": [
		"id",
		"version",
		"supports",
		"contributes"
	],
	"properties": {
		"id": {
			"type": "string",
			"examples": [
				"check-digit"
			]
		},
		"version": {
			"type": "string",
			"examples": [
				"0.1"
			]
		},
		"elementPrefix": {
			"type": "string",
			"default": "",
			"examples": [
				"asseco"
			]
		},
		"propertyPrefix": {
			"type": "string",
			"default": "",
			"examples": [
				"asseco"
			]
		},
		"supports": {
			"type": "object"
		},
		"contributes": {
			"type": "object",
			"required": [
				"definitions"
			],
			"properties": {
				"definitions": {
					"type": "object",
					"additionalProperties": {
						"$ref": "#/definitions/contribution"
					}
				}
			},
			"hostConfig": {
				"type": "object",
				"required": [
					"properties"
				],
				"properties": {
					"properties": {
						"type": "object"
					}
				}
			}
		}
	}
}

=== asseco-see/AdaptiveCards/source/nodejs/schemas/extensions/min-length.json
{
  "id": "min-length",
  "version": "0.1",
  "elementPrefix": "",
  "propertyPrefix": "asseco",
  "supports": {
    "javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
  },
  "contributes": {
    "definitions": {
      "Input.Text": {
        "properties": {
          "minLength": {
            "type": "number",
            "description": "Hint of minimum length characters to collect (may be ignored by some clients).",
            "version": "0.1"
          }
        }
      }
    }
  }
}

=== asseco-see/AdaptiveCards/schemas/extensions/input-chips.json
{
    "id": "textinput-checkdigit-extension",
    "version": "0.1",
    "elementPrefix": "",
    "propertyPrefix": "asseco",
    "supports": {
        "javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
    },
    "contributes": {
	    "definitions": {
			"Input.Chip": {
				  "description": "Describes a chip for use in a ChipSet.",
				  "properties": {
					"type": {
					  "enum": [
						"Input.Chip"
					  ],
					  "description": "Must be `Input.Chip`"
					},
					"id": {
					  "type": "string",
					  "description": "Unique identifier for chip.",
					  "version": "1.4"
					},
					"name": {
					  "type": "string",
					  "description": "Chip name.",
					  "version": "1.4"
					},
					"selected": {
					  "type": "boolean",
					  "description": "Whether or not the chip is selected. Default value is false",
					  "version": "1.4"
					}
				  },
				  "type": "object",
				  "additionalProperties": false,
				  "required": [
					"id",
					"name",
					"selected"
				  ]
			 },
			 "Input.Chips": {
				  "description": "Allows a user to input a Chip.",
				  "properties": {
					"type": {
					  "enum": [
						"Input.Chips"
					  ],
					  "description": "Must be `Input.Chips`"
					},
					"chips": {
					  "type": "array",
					  "items": {
						"$ref": "#/definitions/Input.Chip"
					  },
					  "description": "`Chip` options.",
					  "version": "1.4"
					},
					"value": {
					  "type": "string",
					  "description": "The initial choice (or set of chips) that should be selected. For multi-select, specify a comma-separated string of values.",
					  "version": "1.4"
					},
					"placeholder": {
					  "type": "string",
					  "description": "Description of the input desired. Only visible when no selection has been made, the `style` is `compact` and `isMultiSelect` is `false`",
					  "version": "1.4"
					},
					"color": {
					  "type": "string",
					  "description": "Material color palette of chip. Initial is 'primary'.",
					  "version": "1.4"
					},
					"selectable": {
					  "type": "boolean",
					  "description": "Whether or not chips are selectable. Default is true.",
					  "version": "1.4"
					},
					"removable": {
					  "type": "boolean",
					  "description": "Whether or not chips are removable. Default is true.",
					  "version": "1.4"
					},
					"addOnBlur": {
					  "type": "boolean",
					  "description": "Whether or not the chipEnd event will be emitted when the input is blurred. Default is true.",
					  "version": "1.4"
					},
					"id": {},
					"errorMessage": {},
					"isRequired": {},
					"label": {},
					"fallback": {},
					"height": {},
					"separator": {},
					"spacing": {},
					"isVisible": {},
					"requires": {}
				  },
				  "type": "object",
				  "additionalProperties": false,
				  "required": [
					"chips"
				  ],
				  "allOf": [
					{
					  "$ref": "#/definitions/Extendable.Input"
					}
				  ]
			}
        }
    }
}

=== asseco-see/AdaptiveCards/schemas/extensions/autocomplete.json
{
  "id": "autocomplete",
  "version": "0.1",
  "elementPrefix": "aseeco",
  "propertyPrefix": "",
  "supports": {
    "javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
  },
  "contributes": {
    "definitions": {
      "AutocompleteChoice": {
        "properties": {
          "value": {
            "type": "string",
            "description": "Value for autocomplete choice.",
            "version": "0.1"
          }
        }
      },
      "Input.Autocomplete": {
        "description": "Allows a user to input text with autocomplete option.",
        "properties": {
          "id": {
            "type": "string",
            "description": "Unique identifier for the value. Used to identify collected input when the Submit action is performed.",
            "version": "0.1"
          },
          "value": {
            "type": "string",
            "description": "Initial value that should be selected.",
            "version": "0.1"
          },
          "choices": {
            "type": "AutocompleteChoice[]",
            "description": "Autocomplete choices.",
            "version": "0.1"
          },
          "placeholder": {
            "type": "string",
            "description": "Description of the input desired. Only visible when no selection has been made.",
            "version": "0.1"
          },
          "dataSource": {
            "type": "DataSource",
            "description": "DataSource is an abstraction for using local data (arrays of JavaScript objects) or remote data (web services returning JSON or XML).",
            "version": "0.1"
          }
        }
      }
    }
  }
}

=== asseco-see/AdaptiveCards/source/nodejs/schemas/extensions/input-file-upload.json
{
	"id": "file-upload",
	"version": "0.1",
	"elementPrefix": "aseeco",
	"propertyPrefix": "",
	"supports": {
		"javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
	},
	"contributes": {
		"definitions": {
			"FileUploadMode": {
				"classType": "Enum",
				"type": "FileUploadMode",
				"values": [
					"content",
					"screens"
				]
			},
			"Input.FileUpload": {
				"description": "Allows a user to upload a file.",
				"extends": "Input",
				"properties": {
					"id": {
						"type": "string",
						"description": "Unique identifier for the value. Used to identify collected input when the Submit action is performed.",
						"version": "0.1",
						"required": true
					},
					"mode": {
						"type": "FileUploadMode",
						"description": "File upload mode. Controls where uploaded file should end.",
						"version": "0.1",
						"default": "content",
						"required": false
					},
					"multiple": {
						"type": "boolean",
						"description": "Controls whether multiple file upload is allowed. If true, maximum 5 files are allowed.",
						"version": "0.1",
						"default": false,
						"required": false
					},
					"accept": {
						"type": "string[]",
						"description": "Controls what file extensions are allowed. Extensions must start with \".\".",
						"version": "0.1",
						"required": false
					},
					"repoName": {
						"type": "string",
						"description": "Controls the name of the repository. Used within \"content\" upload mode.",
						"version": "0.1",
						"required": false
					},
					"folderPath": {
						"type": "string",
						"description": "Controls the folder path. Used within \"content\" upload mode.",
						"version": "0.1",
						"required": false
					},
					"style": {
						"type": "ActionStyle",
						"description": "Controls the style of remove file action.",
						"version": "0.1",
						"default": "default",
						"required": false
					}
				}
			}
		}
	}
}

=== asseco-see/AdaptiveCards/schemas/extensions/test-element.json
{
    "id": "test",
    "version": "0.1",
    "elementPrefix": "dp",
    "propertyPrefix": "",
    "supports": {
        "javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
    },
    "contributes": {
        "definitions": {
            "Test": {
                "description": "Allows a user to input a Chip.",
                "properties": {
                    "type": {
                        "type": "string",
                        "enum": ["Test"],
                        "description": "Must be `Test`"
                    },
                    "value": {
                        "type": "string",
                        "description": "The initial choice (or set of chips) that should be selected. For multi-select, specify a comma-separated string of values.",
                        "version": "0.1"
                    },
                    "placeholder": {
                        "type": "string",
                        "description": "Description of the input desired. Only visible when no selection has been made, the `style` is `compact` and `isMultiSelect` is `false`",
                        "version": "0.1"
                    },
                    "color": {
                        "type": "string",
                        "description": "Material color palette of chip. Initial is 'primary'.",
                        "version": "0.1"
                    },
                    "selectable": {
                        "type": "boolean",
                        "description": "Whether or not chips are selectable. Default is true.",
                        "version": "0.1"
                    },
                    "removable": {
                        "type": "boolean",
                        "description": "Whether or not chips are removable. Default is true.",
                        "version": "0.1"
                    },
                    "addOnBlur": {
                        "type": "boolean",
                        "description": "Whether or not the chipEnd event will be emitted when the input is blurred. Default is true.",
                        "version": "0.1"
                    }
                },
                "type": "object",
                "additionalProperties": false,
                "required": ["chips"],
                "extends": "Element"
            }
        }
    }
}
