=== asseco-see/AdaptiveCards/source/nodejs/schemas/extensions/schema/schema.json
{
	"definitions": {
		"contribution": {
			"$schema": "http://json-schema.org/draft-06/schema#",
			"id": "http://adaptivecards.io/schemas/adaptive-card.json",
			"definitions": {
				"Class": {
					"description": "Expresses a class",
					"properties": {
						"classType": {
							"enum": [
								"Class"
							],
							"description": "Must be `Class`"
						},
						"type": {
							"type": "string",
							"description": "The name of the class"
						},
						"description": {
							"type": "string",
							"description": "A description of the class"
						},
						"properties": {
							"type": "object",
							"additionalProperties": {
								"$ref": "#/definitions/Property"
							},
							"description": "Properties of the class"
						},
						"isAbstract": {
							"type": "boolean",
							"description": "Specifies whether this class is abstract"
						},
						"extends": {
							"type": "string",
							"description": "Class that this class extends from"
						},
						"shorthand": {
							"type": "string",
							"description": "Name of one of the properties that represents a shorthand version of this class"
						},
						"$schema": {
							"type": "string",
							"format": "uri",
							"description": "JSON schema for the JSON file"
						}
					},
					"type": "object",
					"additionalProperties": false,
					"required": []
				},
				"Enum": {
					"description": "Expresses an enum",
					"properties": {
						"classType": {
							"enum": [
								"Enum"
							],
							"description": "Must be `Enum`"
						},
						"type": {
							"type": "string",
							"description": "The name of the enum"
						},
						"values": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/EnumValue"
							},
							"description": "The values in the enum"
						},
						"$schema": {
							"type": "string",
							"format": "uri",
							"description": "JSON schema for the JSON file"
						}
					},
					"type": "object",
					"additionalProperties": false,
					"required": [
						"type",
						"values"
					]
				},
				"EnumValue": {
					"description": "Expresses an enum value",
					"anyOf": [
						{
							"type": "string",
							"description": "The name of the enum value"
						},
						{
							"type": "object",
							"properties": {
								"classType": {
									"enum": [
										"EnumValue"
									],
									"description": "Must be `EnumValue`"
								},
								"value": {
									"type": "string",
									"description": "The name of the enum value"
								},
								"description": {
									"type": "string",
									"description": "A description of the enum value"
								}
							},
							"required": [
								"value"
							],
							"additionalProperties": false
						}
					]
				},
				"Property": {
					"properties": {
						"classType": {
							"enum": [
								"Property"
							],
							"description": "Must be `Property`"
						},
						"type": {
							"type": "string",
							"description": "The type of the property"
						},
						"description": {
							"type": "string",
							"description": "A description of the property"
						},
						"version": {
							"type": "string",
							"description": "The version when the property is introduced"
						},
						"required": {
							"type": "boolean",
							"description": "Specifies whether the property is required",
							"default": false
						},
						"shorthands": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/Property"
							},
							"description": "Shorthand alternatives for this property"
						},
						"default": {
							"description": "The default value of this property"
						},
						"examples": {
							"type": "array",
							"description": "Examples of this value"
						}
					},
					"type": "object",
					"additionalProperties": false,
					"required": [
						"type"
					]
				}
			},
			"anyOf": [
				{
					"allOf": [
						{
							"$ref": "#/definitions/Class"
						}
					]
				},
				{
					"allOf": [
						{
							"$ref": "#/definitions/Enum"
						}
					],
					"required": [
						"classType"
					]
				}
			]
		}
	},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://example.com/object1619001505.json",
	"title": "Root",
	"type": "object",
	"required": [
		"id",
		"version",
		"supports",
		"contributes"
	],
	"properties": {
		"id": {
			"type": "string",
			"examples": [
				"check-digit"
			]
		},
		"version": {
			"type": "string",
			"examples": [
				"0.1"
			]
		},
		"elementPrefix": {
			"type": "string",
			"default": "",
			"examples": [
				"asseco"
			]
		},
		"propertyPrefix": {
			"type": "string",
			"default": "",
			"examples": [
				"asseco"
			]
		},
		"supports": {
			"type": "object"
		},
		"contributes": {
			"type": "object",
			"required": [
				"definitions"
			],
			"properties": {
				"definitions": {
					"type": "object",
					"additionalProperties": {
						"$ref": "#/definitions/contribution"
					}
				}
			},
			"hostConfig": {
				"type": "object",
				"required": [
					"properties"
				],
				"properties": {
					"properties": {
						"type": "object"
					}
				}
			}
		}
	}
}

=== asseco-see/AdaptiveCards/schemas/extensions/input-time-period.json
{
  "id": "time-period",
  "version": "0.1",
  "elementPrefix": "aseeco",
  "propertyPrefix": "",
  "supports": {
    "javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
  },
  "contributes": {
    "definitions": {
      "DefaultPeriod": {
        "classType": "Enum",
        "type": "DefaultPeriod",
        "values": ["Y", "M", "D"]
      },
      "Input.TimePeriod": {
        "description": "Allows a user to input a time period in ISO duration.",
        "extends": "Input",
        "properties": {
          "defaultPeriod": {
            "type": "DefaultPeriod",
            "description": "Default input period. Used when 'allowComplex' is set to 'false'.",
            "version": "0.1",
            "default": "M"
          },
          "allowComplex": {
            "type": "boolean",
            "description": "Controls whether complex time period input type is used. If true, enables entering years, months and days separately.",
            "version": "0.1",
            "default": false
          },
					"value": {
						"type": "string",
						"description": "The initial value for this field in ISO duration format.",
						"version": "0.1"
					}
        }
      }
    }
  }
}

=== asseco-see/AdaptiveCards/schemas/extensions/input-decimal.json
{
	"id": "decimal-input",
	"version": "0.1",
	"elementPrefix": "",
	"propertyPrefix": "asseco",
	"supports": {
		"javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
	},
	"contributes": {
		"definitions": {
			"InputNumberType": {
				"classType": "Enum",
				"type": "InputNumberType",
				"values": [
					"default",
					"decimal",
					"currency"
				]
			},
			"DecimalConfig": {
				"classType": "Class",
				"type": "DecimalConfig",
				"properties": {
					"align": {
						"type": "HorizontalAlignment",
						"description": "Horizontal alignment of decimal input value.",
						"version": "0.1",
						"default": "right"
					},
					"allowNegative": {
						"type": "boolean",
						"description": "Whether to allow negative values.",
						"version": "0.1",
						"default": true
					},
					"allowZero": {
						"type": "boolean",
						"description": "Whether to allow zero value.",
						"version": "0.1",
						"default": true
					},
					"decimalSeparator": {
						"type": "string",
						"description": "Decimal separator value.",
						"version": "0.1",
						"default": "."
					},
					"prefix": {
						"type": "string",
						"description": "Prefix for the decimal input value.",
						"version": "0.1"
					},
					"suffix": {
						"type": "string",
						"description": "Suffix for the decimal input value.",
						"version": "0.1"
					},
					"thousandsSeparator": {
						"type": "string",
						"description": "Thousands separator value.",
						"version": "0.1",
						"default": ","
					},
					"appearance": {
						"type": "MaterialComponentAppearance",
						"description": "Appearance type of the component",
						"version": "0.1",
						"default": "outline"
					}
				}
			},
			"Input.Number": {
				"properties": {
					"inputType": {
						"type": "InputNumberType",
						"description": "Controls input number type.",
						"default": "default",
						"version": "0.1"
					},
					"precision": {
						"type": "number",
						"description": "Marks desired decimal places, used when 'inputType' is set to 'decimal' or 'currency'.",
						"default": 2,
						"version": "0.1"
					},
					"decimalOptions": {
						"type": "DecimalConfig",
						"description": "Decimal input options, used when 'inputType' is set to 'decimal' or 'currency'.",
						"version": "0.1"
					},
					"separateThousands": {
						"type": "boolean",
						"description": "Whether to separate thousands, used when 'inputType' is set to 'decimal' or 'currency'.",
						"default": false,
						"version": "0.1"
					},
					"currencies": {
						"type": "string[]",
						"description": "Supported currency list, used when 'inputType' is set to 'currency'.",
						"version": "0.1",
						"example": [
							"EUR",
							"USD",
							"RSD"
						]
					}
				}
			}
		}
	}
}

=== asseco-see/AdaptiveCards/schemas/extensions/input-phone-number.json
{
  "id": "phone-number-input",
  "version": "0.1",
  "elementPrefix": "aseeco",
  "propertyPrefix": "",
  "supports": {
    "javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
  },
  "contributes": {
    "definitions": {
      "PhoneNumberOption": {
        "classType": "Class",
        "type": "PhoneNumberOption",
        "properties": {
					"countryCode": {
            "type": "string",
            "description": "Phone number country code.",
            "version": "0.1",
						"example": "+381",
						"required": true
          },
					"areaCode": {
            "type": "string[]",
            "description": "Phone number area code.",
            "version": "0.1",
						"example": [
							"60", "61"
						],
						"required": true
          },
					"pattern": {
            "type": "string",
            "description": "Regex pattern for additional phone number validation.",
            "version": "0.1"
          },
					"patternMessage": {
            "type": "string",
            "description": "Message displayed when regex validation fails.",
            "version": "0.1"
          }
				}
      },
      "Input.PhoneNumber": {
        "description": "Allows a user to input a phone number.",
        "extends": "Input",
        "properties": {
          "options": {
            "type": "PhoneNumberOption[]",
            "description": "Phone number options.",
            "version": "0.1"
          },
					"optionsConfigurationKey": {
            "type": "string",
            "description": "Options configuration key. Read options from configuration service (used when options are not provided).",
            "version": "0.1",
						"default": "components-ui/phone-number-options"
          }
        }
      }
    }
  }
}

=== asseco-see/AdaptiveCards/schemas/extensions/tabs.json
{
  "id": "tabs",
  "version": "0.1",
  "elementPrefix": "dp",
  "propertyPrefix": "",
  "supports": {
    "javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
  },
  "contributes": {
    "definitions": {
      "Tab": {
        "description": "Defines a container that is part of a TabSet.",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "Tab"
            ],
            "description": "Must be `Tab`",
            "required": true
          },
          "items": {
            "type": "Element[]",
            "description": "Content of the Tab.",
            "version": "0.1",
            "required": true
          },
          "title": {
            "type": "string",
            "description": "The title of the Tab.",
            "version": "0.1",
            "required": true
          },
          "id": {
            "type": "string",
            "description": "A unique identifier associated with the element.",
            "version": "0.1"
          },
          "spacing": {
            "type": "Spacing",
            "description": "Controls the amount of spacing between this element and the preceding element.",
            "version": "0.1"
          },
          "separator": {
            "type": "boolean",
            "description": "When true, draw a separating line at the top of the element.",
            "version": "0.1"
          }
        },
        "type": "object",
        "additionalProperties": false
      },
      "TabSet": {
        "description": "TabSet allows to display content through various tabs.",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "TabSet"
            ],
            "description": "Must be `TabSet`",
            "required": true
          },
          "tabs": {
            "type": "Tab[]",
            "description": "The array of Tabs to divide content.",
            "version": "0.1"
          },
          "id": {
            "type": "string",
            "description": "A unique identifier associated with the element.",
            "version": "0.1",
            "required": true
          },
          "spacing": {
            "type": "Spacing",
            "description": "Controls the amount of spacing between this element and the preceding element.",
            "version": "0.1"
          },
          "separator": {
            "type": "boolean",
            "description": "When true, draw a separating line at the top of the element.",
            "version": "0.1"
          }
        },
        "type": "object",
        "additionalProperties": false
      }
    }
  }
}

=== asseco-see/AdaptiveCards/source/nodejs/schemas/extensions/input-chips.json
{
	"id": "chip-input-chip-list",
	"version": "0.1",
	"elementPrefix": "aseeco",
	"propertyPrefix": "",
	"supports": {
		"javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
	},
	"contributes": {
		"definitions": {
			"ChipStyle": {
				"classType": "Enum",
				"type": "ChipStyle",
				"values": [
					"default",
					"positive",
					"destructive"
				]
			},
			"Chip": {
				"classType": "Class",
				"type": "Chip",
				"description": "Describes a chip for use in a ChipSet.",
				"properties": {
					"type": {
						"type": "string",
						"description": "Must be `Chip`"
					},
					"id": {
						"type": "string",
						"description": "Unique identifier for chip.",
						"version": "0.1",
						"required": true
					},
					"name": {
						"type": "string",
						"description": "Chip name.",
						"version": "0.1",
						"required": true
					},
					"selected": {
						"type": "boolean",
						"description": "Whether or not the chip is selected. Default value is true",
						"version": "0.1",
						"required": true
					},
					"icon": {
						"type": "string",
						"description": "Material icon name of icon that is added left side of Chip name",
						"version": "0.1",
						"required": false
					},
					"avatarUrl": {
						"type": "boolean",
						"description": "Url of the image that is added left side of Chip name",
						"version": "0.1",
						"required": false
					}
				}
			},
			"Input.Chip": {
				"description": "Allows a user to input a Chip.",
				"extends": "Input",
				"properties": {
					"type": {
						"type": "string",
						"description": "Must be `Input.Chip`"
					},
					"chips": {
						"type": "Chip[]",
						"description": "`Chip` options.",
						"version": "0.1",
						"required": true
					},
					"value": {
						"type": "string",
						"description": "The initial choice (or set of chips) that should be selected. For multi-select, specify a comma-separated string of values.",
						"version": "0.1"
					},
					"placeholder": {
						"type": "string",
						"description": "Description of the input desired. Only visible when no selection has been made, the `style` is `compact` and `isMultiSelect` is `false`",
						"version": "0.1"
					},
					"style": {
						"type": "ChipStyle",
						"description": "Material color palette of chip. Initial is 'default'.",
						"version": "0.1",
						"default": "default"
					},
					"selectable": {
						"type": "boolean",
						"description": "Whether or not chips are selectable. Default is true.",
						"version": "0.1",
						"default": true
					},
					"removable": {
						"type": "boolean",
						"description": "Whether or not chips are removable. Default is true.",
						"version": "0.1",
						"default": true
					},
					"multiple": {
						"type": "boolean",
						"description": "Whether or not chips are multi selectable. Default is true.",
						"version": "0.1",
						"default": true
					},
					"readonly": {
						"type": "boolean",
						"description": "Whether or not input chips is readonly. Default is false.",
						"version": "0.1",
						"default": false
					},
					"icon": {
						"type": "boolean",
						"description": "Material icon name of icon that is added left side of Chip name. Added globally to all chips.",
						"version": "0.1"
					},
					"avatarUrl": {
						"type": "boolean",
						"description": "Url of the image that is added left side of Chip name. Added globally to all chips.",
						"version": "0.1"
					},
					"addOnBlur": {
						"type": "boolean",
						"description": "Whether or not the chipEnd event will be emitted when the input is blurred. Default is true.",
						"version": "0.1"
					}
				}
			},
			"ChipList": {
				"description": "Allows a user to preview a Chip list.",
				"extends": "Element",
				"properties": {
					"type": {
						"type": "string",
						"description": "Must be `ChipList`"
					},
					"chips": {
						"type": "Chip[]",
						"description": "`Chip` options.",
						"version": "0.1",
						"required": true
					},
					"value": {
						"type": "string",
						"description": "The initial choice (or set of chips) that should be selected. For multi-select, specify a comma-separated string of values.",
						"version": "0.1"
					},
					"placeholder": {
						"type": "string",
						"description": "Description of the input desired. Only visible when no selection has been made, the `style` is `compact` and `isMultiSelect` is `false`",
						"version": "0.1"
					},
					"style": {
						"type": "ChipStyle",
						"description": "Material color palette of chip. Initial is 'default'.",
						"version": "0.1",
						"default": "default"
					},
					"selectable": {
						"type": "boolean",
						"description": "Whether or not chips are selectable. Default is true.",
						"version": "0.1",
						"default": true
					},
					"stackOriented": {
						"type": "boolean",
						"description": "Whether or not chips are oriented like a stack. Default is false.",
						"version": "0.1",
						"default": false
					},
					"multiple": {
						"type": "boolean",
						"description": "Whether or not chips are multi selectable. Default is true.",
						"version": "0.1",
						"default": true
					},
					"icon": {
						"type": "boolean",
						"description": "Material icon name of icon that is added left side of Chip name. Added globally to all chips.",
						"version": "0.1"
					},
					"avatarUrl": {
						"type": "boolean",
						"description": "Url of the image that is added left side of Chip name. Added globally to all chips.",
						"version": "0.1"
					}
				}
			}
		}
	}
}

=== asseco-see/AdaptiveCards/source/nodejs/schemas/extensions/open-url-mode.json
{
	"id": "open-url-mode",
	"version": "0.1",
	"elementPrefix": "",
	"propertyPrefix": "asseco",
	"supports": {
		"javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
	},
	"contributes": {
		"definitions": {
			"OpenUrlMode": {
				"classType": "Enum",
				"type": "OpenUrlMode",
				"values": ["default", "download"]
			},
			"Action.OpenUrl": {
				"properties": {
					"mode": {
						"type": "OpenUrlMode",
						"description": "Action.OpenUrl mode.",
						"version": "0.1",
						"default": "default",
						"required": false
					}
				}
			}
		}
	}
}

=== asseco-see/AdaptiveCards/source/nodejs/schemas/extensions/icon.json
{
	"id": "icon",
	"version": "0.1",
	"elementPrefix": "",
	"propertyPrefix": "asseco",
	"supports": {
		"javascript": "https://npmjs.com/package/adaptivecards-icon"
	},
	"contributes": {
		"definitions": {
			"IconColors": {
				"classType": "Enum",
				"type": "IconColors",
				"values": [
					"primary",
					"accent",
					"warn"
				]
			},
			"Icon": {
				"description": "Displays an icon",
				"extends": "Element",
				"properties": {
					"label": {
						"type": "string",
						"description": "Icon label."
					},
					"name": {
						"type": "string",
						"description": "Icon name."
					},
					"color": {
						"type": "IconColors",
						"description": "Predefined set of icon colors."
					},
					"horizontalAlignment": {
						"type": "HorizontalAlignment",
						"description": "Controls how this element is horizontally positioned within its parent."
					},
					"style": {
						"type": "ActionStyle",
						"description": "Controls the style of icon.",
						"version": "0.1",
						"default": "default",
						"required": false
					}
				}
			}
		}
	}
}

=== asseco-see/AdaptiveCards/source/nodejs/schemas/extensions/read-only.json
{
  "id": "readonly",
  "version": "0.1",
  "elementPrefix": "",
  "propertyPrefix": "asseco",
  "supports": {
    "javascript": "https://npmjs.com/package/adaptivecards-autocomplete"
  },
  "contributes": {
    "definitions": {
      "Input.Text": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.Number": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.Date": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.Time": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.Toggle": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.ChoiceSet": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.Choice": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.Classification": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.FileUpload": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.PhoneNumber": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.TimePeriod": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.Lookup": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      },
      "Input.PartyLookup": {
        "properties": {
          "readonly": {
            "type": "boolean",
            "description": "If `true`, render read-only input.",
            "version": "0.1"
          }
        }
      }
    }
  }
}
